refined ddns_update

diff --git a/office/ddns_update b/office/ddns_update
--- a/office/ddns_update
+++ b/office/ddns_update
@@ -9,18 +9,22 @@
 
 ip_addr=$(ifconfig -a | grep -i  "192.168.234" | awk -F' ' '{print $2}' |sed -nr 's/(^|.*[^0-9])(([0-9]+\.){3}[0-9]+).*/\2/p'
 )
-if egrep '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$' <<< $ip_addr ;
-  then echo "got ip: $ip_addr";
-  else echo "the script is not able to get ip"; exit 1;
+if egrep '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$' <<< $ip_addr 2>&1 >/dev/null ;
+  then echo "host ip: $ip_addr";
+  else echo "ops, could not get the host ip"; exit 1;
 fi
+echo "host dns: $(hostname).arkologic.com"
+ip_last_part=$(echo $ip_addr | cut -d '.' -f 4)
 commands=$(cat <<EOF
 server 192.168.234.253
 zone arkologic.com
 key DYNAMIC_DNS_KEY. jCe1DfvHYpBDwVk9zlNq6w==
 update add $(hostname).arkologic.com. 86400 IN A $ip_addr
 send
+zone 234.168.192.in-addr.arpa
+update add $ip_last_part.234.168.192.in-addr.arpa. 86400 PTR $(hostname).arkologic.com.
+send
 quit
 EOF
 )
-echo $commands
-nsupdate -d -v <(echo "$commands")
+nsupdate -v <(echo "$commands")
